FROM python:3.11-slim

# Install g++ compiler
RUN apt-get update && apt-get install -y g++ && apt-get clean

WORKDIR /app

# Copy all project files
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]